-- AlterTable
ALTER TABLE `Order` ADD COLUMN `balance` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `cancelledAt` DATETIME(3) NULL,
    ADD COLUMN `deliveredAt` DATETIME(3) NULL,
    ADD COLUMN `paidAmount` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `promisedAt` DATETIME(3) NULL,
    ADD COLUMN `specifications` JSON NULL,
    ADD COLUMN `status` ENUM('DRAFT', 'QUOTE_SENT', 'APPROVED', 'CANCELLED', 'DELIVERED', 'RECEIVED', 'DIAGNOSIS_PENDING', 'WAITING_PARTS', 'IN_REPAIR', 'REPAIR_COMPLETED', 'SPEC_PENDING', 'MATERIALS_PENDING', 'IN_PRODUCTION', 'QUALITY_CHECK', 'READY_FOR_PICKUP', 'LAYAWAY_OPEN', 'LAYAWAY_EXPIRED') NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN `totalAmount` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `type` ENUM('STANDARD', 'REPAIR', 'MANUFACTURE', 'LAYAWAY') NOT NULL DEFAULT 'STANDARD';

-- CreateTable
CREATE TABLE `Payment` (
    `id` VARCHAR(191) NOT NULL,
    `orderId` VARCHAR(191) NOT NULL,
    `amount` DECIMAL(10, 2) NOT NULL,
    `method` VARCHAR(191) NOT NULL,
    `reference` VARCHAR(191) NULL,
    `recordedBy` VARCHAR(191) NULL,
    `recordedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Payment` ADD CONSTRAINT `Payment_orderId_fkey` FOREIGN KEY (`orderId`) REFERENCES `Order`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
